import { useState, useEffect } from 'react';
import {
  Sparkles,
  X,
  Check,
  AlertTriangle,
  Copy,
  RefreshCw,
  Loader2,
  FileText,
} from 'lucide-react';
import toast from 'react-hot-toast';
import clsx from 'clsx';
import * as api from '../api/client';
import type { Job, TailorResult } from '../api/client';

interface TailorModalProps {
  job: Job;
  onClose: () => void;
}

function scoreColor(score: number): string {
  if (score >= 80) return 'text-emerald-600 bg-emerald-50 ring-emerald-200';
  if (score >= 60) return 'text-amber-600 bg-amber-50 ring-amber-200';
  return 'text-rose-600 bg-rose-50 ring-rose-200';
}

export default function TailorModal({ job, onClose }: TailorModalProps) {
  const [result, setResult] = useState<TailorResult | null>(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);

  const load = async (refresh: boolean) => {
    refresh ? setRegenerating(true) : setLoading(true);
    try {
      const r = await api.tailorApplication(job._id, refresh);
      setResult(r);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Failed to tailor application');
    } finally {
      setLoading(false);
      setRegenerating(false);
    }
  };

  useEffect(() => {
    load(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const copyCover = () => {
    if (!result) return;
    navigator.clipboard.writeText(result.tailoring.coverLetter);
    toast.success('Cover letter copied!');
  };

  const t = result?.tailoring;

  return (
    <div
      className="fixed inset-0 z-50 flex items-start sm:items-center justify-center bg-black/40 p-4 overflow-y-auto"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-2xl shadow-xl w-full max-w-2xl my-8 max-h-[90vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-start justify-between p-6 border-b border-slate-100">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-100 flex items-center justify-center flex-shrink-0">
              <Sparkles size={20} className="text-indigo-600" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900 leading-tight">
                AI-Tailored Application
              </h2>
              <p className="text-sm text-slate-500">
                {job.title} · {job.company}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400"
          >
            <X size={20} />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {loading ? (
            <div className="py-16 text-center">
              <Loader2 size={36} className="mx-auto text-indigo-500 animate-spin mb-4" />
              <p className="text-sm font-medium text-slate-700">
                AI is tailoring your application…
              </p>
              <p className="text-xs text-slate-400 mt-1">
                Analyzing the role and matching it to your profile.
              </p>
            </div>
          ) : t ? (
            <>
              {/* Source + match score */}
              <div className="flex items-center justify-between">
                <span
                  className={clsx(
                    'inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full',
                    result?.source === 'ai'
                      ? 'bg-indigo-50 text-indigo-700'
                      : 'bg-slate-100 text-slate-600'
                  )}
                >
                  <Sparkles size={12} />
                  {result?.source === 'ai' ? 'Generated by Claude' : 'Template (add API key for AI)'}
                </span>
                <div
                  className={clsx(
                    'text-sm font-bold px-3 py-1 rounded-full ring-1',
                    scoreColor(t.matchScore)
                  )}
                >
                  {t.matchScore}% match
                </div>
              </div>

              {/* Summary */}
              <p className="text-sm text-slate-700 leading-relaxed">{t.matchSummary}</p>

              {/* Strengths */}
              {t.strengths.length > 0 && (
                <section>
                  <h3 className="text-sm font-semibold text-slate-900 mb-2">Your strengths</h3>
                  <ul className="space-y-1.5">
                    {t.strengths.map((s, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
                        <Check size={15} className="text-emerald-500 mt-0.5 flex-shrink-0" />
                        {s}
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              {/* Gaps */}
              {t.gaps.length > 0 && (
                <section>
                  <h3 className="text-sm font-semibold text-slate-900 mb-2">Address these gaps</h3>
                  <ul className="space-y-1.5">
                    {t.gaps.map((g, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
                        <AlertTriangle size={15} className="text-amber-500 mt-0.5 flex-shrink-0" />
                        {g}
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              {/* ATS keywords */}
              {t.atsKeywords.length > 0 && (
                <section>
                  <h3 className="text-sm font-semibold text-slate-900 mb-2">
                    ATS keywords to include
                  </h3>
                  <div className="flex flex-wrap gap-1.5">
                    {t.atsKeywords.map((k, i) => (
                      <span
                        key={i}
                        className="text-xs font-medium px-2.5 py-1 bg-slate-100 text-slate-700 rounded-lg"
                      >
                        {k}
                      </span>
                    ))}
                  </div>
                </section>
              )}

              {/* Resume tips */}
              {t.resumeTips.length > 0 && (
                <section>
                  <h3 className="text-sm font-semibold text-slate-900 mb-2">Resume tips</h3>
                  <ol className="space-y-2">
                    {t.resumeTips.map((tip, i) => (
                      <li key={i} className="flex items-start gap-2.5 text-sm text-slate-600">
                        <span className="flex-shrink-0 w-5 h-5 rounded-full bg-indigo-100 text-indigo-600 text-xs font-bold flex items-center justify-center mt-0.5">
                          {i + 1}
                        </span>
                        {tip}
                      </li>
                    ))}
                  </ol>
                </section>
              )}

              {/* Cover letter */}
              <section>
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-sm font-semibold text-slate-900 flex items-center gap-1.5">
                    <FileText size={15} className="text-slate-400" /> Cover letter
                  </h3>
                  <button
                    onClick={copyCover}
                    className="inline-flex items-center gap-1.5 text-xs font-medium text-indigo-600 hover:text-indigo-800 px-2 py-1 rounded-lg hover:bg-indigo-50 transition-colors"
                  >
                    <Copy size={13} /> Copy
                  </button>
                </div>
                <div className="rounded-xl border border-slate-200 bg-slate-50 p-4">
                  <pre className="whitespace-pre-wrap font-sans text-sm text-slate-700 leading-relaxed">
                    {t.coverLetter}
                  </pre>
                </div>
              </section>
            </>
          ) : (
            <p className="text-sm text-slate-500 text-center py-12">
              Couldn't generate a tailored application. Please try again.
            </p>
          )}
        </div>

        {/* Footer */}
        {!loading && (
          <div className="flex items-center justify-between gap-3 p-4 border-t border-slate-100">
            <button
              onClick={() => load(true)}
              disabled={regenerating}
              className="btn-secondary flex items-center gap-2 text-sm"
            >
              {regenerating ? (
                <Loader2 size={15} className="animate-spin" />
              ) : (
                <RefreshCw size={15} />
              )}
              Regenerate
            </button>
            <button onClick={onClose} className="btn-primary text-sm px-6">
              Done
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
